// Generated by scripts/build-browser-contracts.mjs from packages/contracts/src.
import * as v from "./browser-validation.ts";
/**
 * 统一响应包装与错误码 —— 见 docs/refactor/03-api-contract.md §1、§2。
 *
 * ERROR_CODES 的顺序与文档 §2.3 表格一致(先 13 个通用码,再 8 个专用业务码)。
 * scripts/check-api-contract.mjs 会逐字对账,改一边必须改另一边。
 */
export const API_BASE_PATH = "/api/v1";
/** 字符串 "v1",不是数字 1。见 03 §7 规则 5。 */
export const API_VERSION = "v1";
/** 请求体上限,与现有 local-http-service.js 的 MAX_BODY_BYTES 一致 */
export const MAX_BODY_BYTES = 1024 * 1024;
/** 后端未就绪时前端的排队上限 —— 见 03 §1.2 第 4、5 条 */
export const REQUEST_QUEUE_LIMIT = { maxRequests: 50, maxWaitMs: 10000 } as const;
export const HEADER = {
    authorization: "Authorization",
    contentType: "Content-Type",
    requestId: "X-Request-Id",
    idempotencyKey: "Idempotency-Key",
    client: "X-Client",
} as const;
export const CLIENT_KINDS = ["control-center", "pet-window", "mcp"] as const;
export type ClientKind = (typeof CLIENT_KINDS)[number];
export const ERROR_CODES = [
    "VALIDATION_FAILED",
    "UNAUTHORIZED",
    "PERMISSION_DENIED",
    "NOT_FOUND",
    "CONFLICT",
    "PAYLOAD_TOO_LARGE",
    "UNSUPPORTED_MEDIA_TYPE",
    "LOCKED",
    "RATE_LIMITED",
    "INTERNAL",
    "PROVIDER_ERROR",
    "BACKEND_UNAVAILABLE",
    "PROVIDER_TIMEOUT",
    "PLUGIN_MANIFEST_INVALID",
    "PLUGIN_ALREADY_RUNNING",
    "PLUGIN_NATIVE_NOT_APPROVED",
    "PET_PACK_INCOMPATIBLE",
    "ACTION_FRAMES_MISSING",
    "AI_KEY_NOT_CONFIGURED",
    "JOB_NOT_CANCELABLE",
    "MIGRATION_REQUIRED",
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];
/**
 * 通用码 → HTTP 状态码。
 * 8 个专用业务码搭配 400 / 409 / 423,由抛出点决定,故不在此表。
 */
export const ERROR_HTTP_STATUS = {
    VALIDATION_FAILED: 400,
    UNAUTHORIZED: 401,
    PERMISSION_DENIED: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    PAYLOAD_TOO_LARGE: 413,
    UNSUPPORTED_MEDIA_TYPE: 415,
    LOCKED: 423,
    RATE_LIMITED: 429,
    INTERNAL: 500,
    PROVIDER_ERROR: 502,
    BACKEND_UNAVAILABLE: 503,
    PROVIDER_TIMEOUT: 504,
} as const satisfies Partial<Record<ErrorCode, number>>;
/**
 * 可重试码。前端只允许对「retryable 且请求本身幂等」的调用自动重试;
 * 写操作即使 retryable 也必须带 Idempotency-Key 才能自动重试。
 */
export const RETRYABLE_ERROR_CODES = [
    "CONFLICT",
    "LOCKED",
    "RATE_LIMITED",
    "INTERNAL",
    "PROVIDER_ERROR",
    "BACKEND_UNAVAILABLE",
    "PROVIDER_TIMEOUT",
] as const;
export const isRetryableErrorCode = (code: string): boolean => (RETRYABLE_ERROR_CODES as readonly string[]).includes(code);
export const responseMetaSchema = v.object({
    requestId: v.pipe(v.string(), v.minLength(1)),
    elapsedMs: v.optional(v.pipe(v.pipe(v.number(), v.integer()), v.minValue(0))),
});
export type ResponseMeta = v.InferOutput<typeof responseMetaSchema>;
export const apiErrorSchema = v.object({
    code: v.picklist(ERROR_CODES),
    message: v.pipe(v.string(), v.minLength(1)),
    details: v.optional(v.record(v.string(), v.unknown())),
    retryable: v.boolean(),
    requestId: v.pipe(v.string(), v.minLength(1)),
});
export type ApiError = v.InferOutput<typeof apiErrorSchema>;
export const apiFailureSchema = v.object({
    ok: v.literal(false),
    error: apiErrorSchema,
});
export type ApiFailure = v.InferOutput<typeof apiFailureSchema>;
export const apiSuccessSchema = <T extends v.GenericSchema>(data: T) => v.object({ ok: v.literal(true), data, meta: responseMetaSchema });
export const apiListSchema = <T extends v.GenericSchema>(item: T) => apiSuccessSchema(v.object({
    items: v.array(item),
    total: v.pipe(v.pipe(v.number(), v.integer()), v.minValue(0)),
    cursor: v.optional(v.nullable(v.string())),
}));
export type ApiSuccess<T> = {
    ok: true;
    data: T;
    meta: ResponseMeta;
};
export type ApiList<T> = ApiSuccess<{
    items: T[];
    total: number;
    cursor?: string | null;
}>;
export type ApiResult<T> = ApiSuccess<T> | ApiFailure;
export const isApiFailure = <T>(r: ApiResult<T>): r is ApiFailure => r.ok === false;

/**
 * Job 契约 —— 见 docs/refactor/03-api-contract.md §6 与 04-subsystems.md §2。
 * 长任务(图像生成实测约 265 秒,超时 420 秒)不能走同步请求/响应,统一走 Job。
 */
export const JOB_KINDS = [
    "image.generate",
    "sprite.generate",
    "sprite.evaluate",
    "creator.character",
    "creator.workflow",
    "creator.export",
    "hatch.run",
    "plugin.install",
    "plugin.install.github",
    "plugin.command",
    "plugin.sync-bundled",
    "pet-pack.import",
    "pet-pack.export",
    "actions.import-frames",
    "catalog.install",
    "about.check-updates",
    "store.migrate",
] as const;
export type JobKind = (typeof JOB_KINDS)[number];
export const JOB_STATUSES = ["queued", "running", "succeeded", "failed", "canceled", "interrupted"] as const;
export type JobStatus = (typeof JOB_STATUSES)[number];
/** 已落地、不再变化的状态 */
export const TERMINAL_JOB_STATUSES = ["succeeded", "failed", "canceled"] as const;
/** 允许 POST /jobs/{id}/retry 的状态。interrupted 来自后端重启遗留。 */
export const RETRYABLE_JOB_STATUSES = ["failed", "interrupted"] as const;
/**
 * 重试次数。03 §6.2 的示例写 maxAttempts: 2,04 §2.5 写默认 1 —— 两者并不冲突:
 * 只有 provider / 网络类任务才自动重试第二次,本地文件与数据库类一律 1 次。
 * 这张表就是那条口径的唯一落点。
 */
export const DEFAULT_MAX_ATTEMPTS = 1;
export const NETWORK_MAX_ATTEMPTS = 2;
export const MAX_ATTEMPTS_BY_KIND = {
    "image.generate": NETWORK_MAX_ATTEMPTS,
    "sprite.generate": NETWORK_MAX_ATTEMPTS,
    "sprite.evaluate": NETWORK_MAX_ATTEMPTS,
    "creator.character": NETWORK_MAX_ATTEMPTS,
    "creator.workflow": NETWORK_MAX_ATTEMPTS,
    "creator.export": DEFAULT_MAX_ATTEMPTS,
    "hatch.run": NETWORK_MAX_ATTEMPTS,
    "plugin.install": DEFAULT_MAX_ATTEMPTS,
    "plugin.install.github": NETWORK_MAX_ATTEMPTS,
    "plugin.command": DEFAULT_MAX_ATTEMPTS,
    "plugin.sync-bundled": DEFAULT_MAX_ATTEMPTS,
    "pet-pack.import": DEFAULT_MAX_ATTEMPTS,
    "pet-pack.export": DEFAULT_MAX_ATTEMPTS,
    "actions.import-frames": DEFAULT_MAX_ATTEMPTS,
    "catalog.install": NETWORK_MAX_ATTEMPTS,
    "about.check-updates": NETWORK_MAX_ATTEMPTS,
    "store.migrate": DEFAULT_MAX_ATTEMPTS,
} as const satisfies Record<JobKind, number>;
/** 进度事件节流窗口 —— 见 04 §2.4 */
export const JOB_PROGRESS_THROTTLE_MS = 500;
export const jobProgressSchema = v.object({
    phase: v.pipe(v.string(), v.minLength(1)),
    percent: v.pipe(v.pipe(v.number(), v.minValue(0)), v.maxValue(100)),
    message: v.optional(v.string()),
});
export type JobProgress = v.InferOutput<typeof jobProgressSchema>;
export const jobSchema = v.object({
    jobId: v.pipe(v.string(), v.minLength(1)),
    kind: v.picklist(JOB_KINDS),
    status: v.picklist(JOB_STATUSES),
    progress: v.nullable(jobProgressSchema),
    cancelable: v.boolean(),
    attempt: v.pipe(v.pipe(v.number(), v.integer()), v.minValue(1)),
    maxAttempts: v.pipe(v.pipe(v.number(), v.integer()), v.minValue(1)),
    resourceKey: v.optional(v.nullable(v.string())),
    createdAt: v.string(),
    startedAt: v.nullable(v.string()),
    finishedAt: v.nullable(v.string()),
    result: v.nullable(v.unknown()),
    error: v.nullable(v.object({ code: v.string(), message: v.string(), retryable: v.boolean() })),
    canRetry: v.boolean(),
    /** input 一律脱敏后存储,不得落 prompt 全文以外的密钥类字段 */
    input: v.object({ redacted: v.literal(true), summary: v.string() }),
});
export type Job = v.InferOutput<typeof jobSchema>;
/** 所有创建长任务的端点统一返 202 Accepted,body 为此形状 */
export const jobCreatedSchema = v.object({
    jobId: v.pipe(v.string(), v.minLength(1)),
    kind: v.picklist(JOB_KINDS),
    status: v.literal("queued"),
    createdAt: v.string(),
    estimatedMs: v.nullable(v.pipe(v.pipe(v.number(), v.integer()), v.minValue(1))),
    pollUrl: v.pipe(v.string(), v.minLength(1)),
});
export type JobCreated = v.InferOutput<typeof jobCreatedSchema>;
export const isTerminalJobStatus = (s: string): boolean => (TERMINAL_JOB_STATUSES as readonly string[]).includes(s);
export const isRetryableJobStatus = (s: string): boolean => (RETRYABLE_JOB_STATUSES as readonly string[]).includes(s);

/**
 * SSE 主题与事件目录 —— 见 docs/refactor/03-api-contract.md §5。
 *
 * 本文件是「后端实际发出的事件名」的唯一枚举源。
 * scripts/check-api-contract.mjs 会拿 EVENT_NAMES / EVENT_TOPIC 与文档 §5
 * 的表格逐字对账 —— 03 §5 曾漏登 system.jobs-recovered 与 system.events-dropped
 * 两项,就是因为它们只写在子系统篇里而没回归到契约。
 */
export const SSE_TOPICS = ["pet", "jobs", "plugins", "ai", "logs", "settings", "catalog", "system"] as const;
export type SseTopic = (typeof SSE_TOPICS)[number];
/** system 无论是否出现在 ?topics= 里都会下发:降级与关闭通知不能被漏订 */
export const ALWAYS_DELIVERED_TOPICS = ["system"] as const;
/** 前端默认订阅集合。logs 只在日志面板打开时追加订阅。 */
export const DEFAULT_SUBSCRIBED_TOPICS = ["pet", "jobs", "plugins", "ai", "settings", "catalog"] as const;
export const EVENT_SETTINGS_CHANGED = "settings.changed" as const;
export const EVENT_SYSTEM_EVENTS_DROPPED = "system.events-dropped" as const;
export const EVENT_BACKEND_SHUTTING_DOWN = "backend.shutting-down" as const;
export const EVENT_CATALOG_REFRESHED = "catalog.refreshed" as const;
export const EVENT_PET_PACK_ACTIVATED = "pet.pack-activated" as const;
export const EVENT_ACTIONS_CHANGED = "pet.actions-changed" as const;
export const EVENT_NAMES = [
    "job.created",
    "job.progress",
    "job.succeeded",
    "job.failed",
    "job.canceled",
    "plugin.installed",
    "plugin.removed",
    "plugin.status-changed",
    "plugin.log",
    "ai.chat-delta",
    "ai.chat-done",
    "ai.talk-utterance",
    "pet.pack-activated",
    "pet.actions-changed",
    "settings.changed",
    "catalog.refreshed",
    "log.appended",
    "backend.shutting-down",
    "backend.degraded",
    "system.jobs-recovered",
    "system.events-dropped",
] as const;
export type EventName = (typeof EVENT_NAMES)[number];
export const EVENT_TOPIC: Record<EventName, SseTopic> = {
    "job.created": "jobs",
    "job.progress": "jobs",
    "job.succeeded": "jobs",
    "job.failed": "jobs",
    "job.canceled": "jobs",
    "plugin.installed": "plugins",
    "plugin.removed": "plugins",
    "plugin.status-changed": "plugins",
    "plugin.log": "plugins",
    "ai.chat-delta": "ai",
    "ai.chat-done": "ai",
    "ai.talk-utterance": "ai",
    "pet.pack-activated": "pet",
    "pet.actions-changed": "pet",
    "settings.changed": "settings",
    "catalog.refreshed": "catalog",
    "log.appended": "logs",
    "backend.shutting-down": "system",
    "backend.degraded": "system",
    "system.jobs-recovered": "system",
    "system.events-dropped": "system",
};
/** 心跳:后端每 15s 发一行 ": ping" 注释 */
export const SSE_HEARTBEAT_MS = 15000;
/** 前端 45s 无帧即重连 */
export const SSE_RECONNECT_AFTER_SILENCE_MS = 45000;
/** 重连退避。不用 EventSource(它带不了 Authorization),走 fetch + ReadableStream。 */
export const SSE_RECONNECT_BACKOFF_MS = [1000, 2000, 5000, 10000] as const;
/** 单连接缓冲上限,超限丢最旧的 log.appended 并发一条 system.events-dropped */
export const SSE_BUFFER_MAX_FRAMES = 1000;
/** 后端重启后的 Job 恢复结果 —— 见 04 §2.6 */
export const jobsRecoveredSchema = v.object({
    interrupted: v.array(v.string()),
    requeued: v.array(v.string()),
});
export type JobsRecovered = v.InferOutput<typeof jobsRecoveredSchema>;
/** 背压丢帧通告。前端收到即视为本地缓存不再可信,需全量重拉受影响 topic。 */
export const eventsDroppedSchema = v.object({
    topic: v.picklist(SSE_TOPICS),
    dropped: v.pipe(v.pipe(v.number(), v.integer()), v.minValue(1)),
    since: v.string(),
});
export type EventsDropped = v.InferOutput<typeof eventsDroppedSchema>;
export const backendDegradedSchema = v.object({ reason: v.pipe(v.string(), v.minLength(1)) });
export const isEventName = (name: string): name is EventName => (EVENT_NAMES as readonly string[]).includes(name);
export const topicOf = (name: EventName): SseTopic => EVENT_TOPIC[name];

/**
 * 设置读写契约 —— 见 docs/refactor/03-api-contract.md §4.2。
 *
 * 关键变更:SETTINGS_SAVE 不得直译为 PUT /settings。
 * 现状是全量读-改-写,拆成两个进程后必然丢写。改为 PATCH + 版本号乐观锁,
 * 冲突返 409 CONFLICT,由前端重拉后重放。
 */
export const settingsPatchRequestSchema = v.object({
    /** 前端上次读到的 version。不匹配即 409,不做静默覆盖。 */
    ifVersion: v.pipe(v.pipe(v.number(), v.integer()), v.minValue(0)),
    /** 只提交变更过的字段,键为点分路径,如 "pet.scale" */
    patch: v.record(v.string(), v.unknown()),
});
export type SettingsPatchRequest = v.InferOutput<typeof settingsPatchRequestSchema>;
export const settingsPatchResponseSchema = v.object({
    version: v.pipe(v.pipe(v.number(), v.integer()), v.minValue(0)),
    changedPaths: v.array(v.string()),
});
export type SettingsPatchResponse = v.InferOutput<typeof settingsPatchResponseSchema>;
export const settingsEnvelopeSchema = v.object({
    version: v.pipe(v.pipe(v.number(), v.integer()), v.minValue(0)),
    /** 已脱敏:密钥类字段只返回存在性与尾号 */
    values: v.record(v.string(), v.unknown()),
});
export type SettingsEnvelope = v.InferOutput<typeof settingsEnvelopeSchema>;
/** settings.changed 只告知变更路径,前端据此决定失效哪些 query */
export const settingsChangedSchema = v.object({
    paths: v.pipe(v.array(v.string()), v.minLength(1)),
    version: v.pipe(v.pipe(v.number(), v.integer()), v.minValue(0)),
});
export type SettingsChanged = v.InferOutput<typeof settingsChangedSchema>;
/** 密钥类字段的对外形状:任何响应体都不得含明文 */
export const secretStatusSchema = v.object({
    configured: v.boolean(),
    maskedTail: v.nullable(v.string()),
});
export type SecretStatus = v.InferOutput<typeof secretStatusSchema>;
/** Renderer-writable settings paths. Host-normalized paths are included for contract reconciliation but rejected by HTTP. */
export const SETTINGS_CANONICAL_PATHS = [
    // Legacy backend stores may still contain flattened pet paths during migration.
    "pet.scale",
    "scale", "walkSpeed", "walkDuration", "bubbleDuration", "menuPosition", "autoStart",
    "selectedCursorId", "customCursor", "customCursors", "hiddenCursorIds", "customCursorScope",
    "petBehavior.grounded", "petBehavior.home.enabled", "petBehavior.home.radius",
    "petBehavior.home.anchor", "petBubbleChat.enabled", "petBubbleChat.autoPopup",
    "petBubbleChat.autoHide", "petBubbleChat.pinOnInteraction",
] as const;
/** Settings paths that may only be persisted across the private Shell↔Backend process bridge. */
export const SETTINGS_TRUSTED_PATHS = ["petBehavior.home.anchor"] as const;
/** 进程内缓存 GET /settings 的时长 —— 03 §10 的超标处理手段 */
export const SETTINGS_CACHE_TTL_MS = 5000;
