const assert = require("node:assert/strict")
const { test } = require("node:test")
const { createServer } = require("node:http")
const { once } = require("node:events")

test("HTTP access logs persist final response status without query strings or credentials", async (t) => {
	const { createRouter } = await import("../../services/backend/http/router.js")
	const { accessLog, bearerAuth, errorBoundary, requestId, sendSuccess, ApiError, createAccessLogBuffer } = await import("../../services/backend/http/middleware.js")
	const { openDatabase } = await import("../../services/backend/store/db.js")
	const { migrate } = await import("../../services/backend/store/migrate.js")
	const { createLogsRepository } = await import("../../services/backend/store/repositories/logs.js")
	const db = await openDatabase({ file: ":memory:" })
	migrate({ db })
	const logs = createLogsRepository({ db })
	const warnings = []
	const buffer = createAccessLogBuffer()
	const router = createRouter()
	router.use(requestId()).use(errorBoundary()).use(accessLog({ buffer, appendHttp: logs.appendHttp, logger: { warn: (...args) => warnings.push(args) } })).use(bearerAuth({ getSessionToken: () => "probe-token" }))
	router.get("/ok", (ctx) => sendSuccess(ctx, { value: true }))
	router.get("/invalid", () => { throw new ApiError("VALIDATION_FAILED", "invalid input") })
	router.get("/failure", () => { throw new Error("internal failure") })
	const server = createServer((req, res) => { void router.handle(req, res) })
	server.listen(0, "127.0.0.1")
	await once(server, "listening")
	t.after(async () => {
		await new Promise((resolve) => { server.close(resolve); server.closeAllConnections() })
		db.close()
	})
	for (const [path, token, expected] of [["ok", "probe-token", 200], ["ok", "invalid-token", 401], ["invalid", "probe-token", 400], ["failure", "probe-token", 500]]) {
		const response = await fetch(`http://127.0.0.1:${server.address().port}/api/v1/${path}?private=secret-query`, { headers: { authorization: `Bearer ${token}` } })
		await response.text()
		assert.equal(response.status, expected)
	}
	assert.deepEqual(buffer.list().map((entry) => entry.status), [200, 401, 400, 500])
	const stored = logs.listHttp().reverse()
	assert.equal(stored.length, 4)
	assert.deepEqual(stored.map((entry) => entry.status), [200, 401, 400, 500])
	assert.ok(stored.every((entry) => Number.isFinite(entry.at)))
	assert.doesNotMatch(JSON.stringify(stored), /secret-query|probe-token|invalid-token/)
	assert.equal(warnings.filter(([message]) => message.includes("写入 HTTP")).length, 0)
})
